config/routes.rb
Bloccit::Application.routes.draw do
  devise_for :users
   resources :users, only: [:update]
  resources :topics do
    resources :posts, except: [:index]
  end
 
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
    mount_uploader :post_image, PostsUploader
  has_many :votes, dependent: :destroy
  belongs_to :user
  belongs_to :topic

  default_scope { order('rank DESC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  after_create :create_vote

  def markdown_title
    render_as_markdown title
  end

  def markdown_body
    render_as_markdown body
  end

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
     new_rank = points + age_in_days
 
     update_attribute(:rank, new_rank)
   end


  private
  def render_as_markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer,extensions)
    (redcarpet.render text).html_safe
  end

   def create_vote
    user.votes.create(value: 1, post: self)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  #   @posts = Post.all
  #   authorize @posts
  # end

  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    #binding.pry
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving this post. Please try again. "
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    
    #@post.update_attributes(params.require[:post].permit(:title,:body))

    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated"
      redirect_to [@topic, @post]
    else
      flash[:error]="There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    title = @post.title

    authorize @post
    
    if @post.destroy
      flash[:notice] = "\"#{title}\"is deleted successfully"
      redirect_to [@topic]
    else
      flash[:error] = "Error deleting post."
      render :show
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>

  <% if post.post_image? %>
    <div class="form-group">
      <p>Current image</p>
           <%= image_tag( post.post_image.url ) %>
         </div>
       <% end %>
       <div class="form-group">
         <%= f.label :post_image %>
         <%= f.file_field :post_image %>
         <%= f.hidden_field :post_image_cache %>
       </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %> 

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p> Guidelines for posts.</p>
    <ul>
      <li>Make sure the it rhymes. </li>
      <li>Don't use the letter "A" </li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>

  <div class="col-md-8">
      <%= render partial: 'form', locals: { topic: @topic, post: @post } %>

  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure the it rhymes.</li>
      <li>Don't use the letter 'A'</li>
      <li>The incessant use the hashtags will get you banned.</li>
    </ul>
  </div> <!-- end of col-md-4 -->

  <div = class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>

  </div> <!-- end of col-md-8 -->
</div> <!-- end of row -->

app/views/posts/show.html.erb
 <%= render partial: 'votes/voter', locals:{ post: @post } %>
 <h1>
    <%= image_tag(@post.post_image.thumb.url) if @post.post_image? %> <%=@post.markdown_title %>
  </h1> 

<div class="row">
  <div class="col-md-8">
    <small>
       <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
       submitted <%= time_ago_in_words(@post.created_at) %> ago by
       <%= @post.user.name %>
    </small>

    <p><%= @post.markdown_body %></p>

    <p class="comment_input"> <%= render partial: 'comments/form', locals: { topic: @topic, post: @post, comment: @comment } %> </p>
  <%= render partial: 'comments/comment'%>
  <%= will_paginate @comments %>
  </div>

  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@post).destroy? %>
      <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this post?"} %>
    <% end %>
       <div>
        <h3><%= pluralize(@post.points, 'point') %></h3>
        <small>
          <%= pluralize(@post.up_votes, 'up vote') %>, 
          <%= pluralize(@post.down_votes, 'down vote') %>
        </small>
   </div>
  </div>  

</div>